# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/antonio/UFJF/DCC062/LotteryScheduling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/antonio/UFJF/DCC062/LotteryScheduling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antonio/UFJF/DCC062/LotteryScheduling/CMakeFiles /home/antonio/UFJF/DCC062/LotteryScheduling//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antonio/UFJF/DCC062/LotteryScheduling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LotteryScheduling

# Build rule for target.
LotteryScheduling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LotteryScheduling
.PHONY : LotteryScheduling

# fast build rule for target.
LotteryScheduling/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/build
.PHONY : LotteryScheduling/fast

src/lottery.o: src/lottery.c.o
.PHONY : src/lottery.o

# target to build an object file
src/lottery.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/lottery.c.o
.PHONY : src/lottery.c.o

src/lottery.i: src/lottery.c.i
.PHONY : src/lottery.i

# target to preprocess a source file
src/lottery.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/lottery.c.i
.PHONY : src/lottery.c.i

src/lottery.s: src/lottery.c.s
.PHONY : src/lottery.s

# target to generate assembly for a file
src/lottery.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/lottery.c.s
.PHONY : src/lottery.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/main.c.s
.PHONY : src/main.c.s

src/process.o: src/process.c.o
.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/process.c.s
.PHONY : src/process.c.s

src/sched.o: src/sched.c.o
.PHONY : src/sched.o

# target to build an object file
src/sched.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/sched.c.o
.PHONY : src/sched.c.o

src/sched.i: src/sched.c.i
.PHONY : src/sched.i

# target to preprocess a source file
src/sched.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/sched.c.i
.PHONY : src/sched.c.i

src/sched.s: src/sched.c.s
.PHONY : src/sched.s

# target to generate assembly for a file
src/sched.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LotteryScheduling.dir/build.make CMakeFiles/LotteryScheduling.dir/src/sched.c.s
.PHONY : src/sched.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LotteryScheduling"
	@echo "... src/lottery.o"
	@echo "... src/lottery.i"
	@echo "... src/lottery.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/sched.o"
	@echo "... src/sched.i"
	@echo "... src/sched.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

